[project]
name = "nora-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-index-llms-ollama>=0.5.0",
    "pandas>=2.2.3",
    "sqlmodel>=0.0.22",
    "zimply>=1.1.4",
]
